# Use root/example as user/password credentials
version: '3.1'

networks:
  noep-dev:
    external:
      name: noep-dev

services:
  mariadb:
    container_name: mariadb-01
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: noep
    ports:
      - 3306:3306
    networks:
      - noep-dev

